CC=gcc
BUILD_DIR=bin
SRC_DIR=src
INC_DIR=include
DOC_DIR=doc
INCLUDE=-I$(INC_DIR)
LIBS=-lm -lMLV
CFLAGS=-fdiagnostics-color=always -Wstrict-prototypes -MMD -Wenum-conversion -Wall -pedantic -std=c17 -Og -g
TAR_NAME=SEBAN_SOUIOU_TowerDefense
TAR_CONTENT=$(SRC_DIR)/ $(INC_DIR)/ $(DOC_DIR)/ $(BUILD_DIR)/ assets/ Makefile Doxyfile .gitignore
EXEC=td

SOURCES=$(wildcard $(SRC_DIR)/*.c)
HEADERS=$(wildcard $(INC_DIR)/*.h)

# Get all the .c source files, and prefix them with the build
# path, and suffix them with .o :
OBJS=$(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(SOURCES))
#$(info $(OBJS))

all: $(BUILD_DIR)/$(EXEC)

# Dependencies generated by GCC
-include $(wildcard $(BUILD_DIR)/*.d)

# Create the build directory
$(BUILD_DIR):
	@mkdir --parents $@

# Link final executable
$(BUILD_DIR)/$(EXEC): $(OBJS) | $(BUILD_DIR) # Create build directory if it doesn't exist (order only prerequisite)
	$(CC) $^ -o $@ $(LIBS)

# Compile each source file into an object file
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(INCLUDE) $(CFLAGS) -c $< -o $@

rapport: $(DOC_DIR)/rapport.pdf

$(DOC_DIR)/rapport.pdf: $(DOC_DIR)/rapport.md
	@mkdir --parents $(DOC_DIR)/logos
	@wget --quiet --show-progress --no-clobber -O $(DOC_DIR)/logos/LogoLIGM.png "https://drive.google.com/uc?export=download&confirm=yes&id=1cZjxS6Rwp8LU4Eyahqz0eUS8aH0_VrVB" || true
	@wget --quiet --show-progress --no-clobber -O $(DOC_DIR)/logos/namedlogoUGE.png "https://drive.google.com/uc?export=download&confirm=yes&id=1YGm1N7griuDbJhC6rSgBHrrcOsHKM5xg" || true
	pandoc --toc $< -o $@ --metadata-file=$(DOC_DIR)/metadata.yaml

format: $(SOURCES) $(HEADERS)
	clang-format -i --style=file $^
	clang-tidy --fix $^

clean:
	rm -f $(OBJS)
	rm -f $(BUILD_DIR)/*.d

distclean: clean
	rm -f $(BUILD_DIR)/$(EXEC)

doc: $(SOURCES) $(HEADERS)
	doxygen

archive: distclean rapport $(SOURCES) $(HEADERS) Makefile
	tar --owner=0 --group=0 --mode='a=r,u+rw,a+X' -czf $(TAR_NAME).tar.gz --transform 's,^,$(TAR_NAME)/,' $(TAR_CONTENT)

rendu:
	@$(MAKE) --no-print-directory clean
	@$(MAKE) --no-print-directory doc
	@$(MAKE) --no-print-directory rapport
	@$(MAKE) --no-print-directory archive

.PHONY: clean all
